### ISSUE TITLE
Still laggy

### ISSUE THREAD

**Issue by flplv** [mnalis/ssh-line-mode#1]
Hey, just did a default install, following the instructions in the TXT file, used the `sshlm user@host` and nothing changed, it is still laggy char-by-char in my very slow ssh connection.

ubuntu 17.04 here

**Comment by mnalis** [comment]
`USAGE.txt` is file that should contain information on usage. By default, after `sshlm user@host` you will still be in slow char-by-char mode as you notice. You must then press hotkey (by default <kbd>ctrl</kbd> + <kbd>]</kbd>) to enter fast local line editing mode. 

After you check that it works, you may modify your `PS1` prompt to enable automatic startup of local line editing mode on every shell prompt as detailed in `USAGE.txt`.

**Comment by flplv** [comment]
Ok, it works, now I feel silly.

May I add some ideas:
1) to have line mode as default, after all, that's just why I'm launching the `sshlm`.
2) to have a line printed at the first line after the program launches saying: "Use ctrl+] to toggle line mode".

**Comment by mnalis** [comment]
thanks for suggestion, added help in e2ad4873acc9be48f9f55eeeb2e29e70df1cbf4f
